using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AlohaGeneratorSimple
{
    internal enum AlohaTransactionType
    {
        Unknown = 0,
        Accept_Table = 19,
        Add_Check = 13,
        Add_Item = 8,
        Adjust_Payment = 30,
        Apply_Comp = 33,
        Apply_Grat = 36,
        Apply_Payment = 26,
        Apply_Promo = 32,
        Assign_Drawer = 56,
        Authorize_Payment = 27,
        Balance_Due = 48,
        Break_End = 6,
        Break_Start = 5,
        Cancel_Item = 9,
        Change_Due = 57,
        Checkout = 42,
        Clear_Password = 58,
        Clock_In = 3,
        Clock_Out = 4,
        Close_Check = 22,
        Current_Time = 54,
        Decline_Payment = 28,
        Delete_Checkout = 44,
        Delete_Clockout = 45,
        Delete_Comp = 35,
        Delete_Grat = 37,
        Delete_Payment = 31,
        Delete_Promo = 34,
        Drawer_Closed = 39,
        Drawer_Open = 38,
        Force_Authorization = 29,
        Get_Check = 20,
        Hold_Item = 12,
        Log_In = 1,
        Log_Out = 2,
        Move_Items = 14,
        No_Sale = 46,
        Open_Item = 53,
        Open_Table_Tab = 7,
        Order_Items = 11,
        Paid_In = 40,
        Paid_Out = 41,
        Print_Check = 15,
        Print_Checkout = 43,
        Recall_Check = 24,
        Refund_Items = 51,
        Refund_Order = 50,
        Reopen_Check = 23,
        Report_Ran = 55,
        Return_Check = 21,
        Select_Order = 25,
        Split_Item = 16,
        Subtotal = 49,
        Tax = 47,
        Tax_Exempt = 52,
        Total = 59,
        Transfer_Check = 17,
        Transfer_Table = 18,
        Void_Item = 10,
        Void_Order = 60
    }
}
