using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AlohaPcapParser
{
    public enum TransactionTypes
    {
        ACCEPT_TABLE = 19,
        ADD_CHECK = 13,
        ADD_ITEM = 8,
        ADJUST_PAYMENT = 30,
        APPLY_COMP = 33,
        APPLY_GRAT = 36,
        APPLY_PAYMENT = 26,
        APPLY_PROMO = 32,
        ASSIGN_DRAWER = 56,
        AUTHORIZE_PAYMENT = 27,
        BALANCE_DUE = 48,
        BREAK_END = 6,
        BREAK_START = 5,
        CANCEL_ITEM = 9,
        CHANGE_DUE = 57,
        CHECKOUT = 42,
        CLEAR_PASSWORD = 58,
        CLOCK_IN = 3,
        CLOCK_OUT = 4,
        CLOSE_CHECK = 22,
        CURRENT_TIME = 54,
        DECLINE_PAYMENT = 28,
        DELETE_CHECKOUT = 44,
        DELETE_CLOCKOUT = 45,
        DELETE_COMP = 35,
        DELETE_GRAT = 37,
        DELETE_PAYMENT = 31,
        DELETE_PROMO = 34,
        DRAWER_CLOSED = 39,
        DRAWER_OPEN = 38,
        FORCE_AUTHORIZATION = 29,
        GET_CHECK = 20,
        HOLD_ITEM = 12,
        LOG_IN = 1,
        LOG_OUT = 2,
        MOVE_ITEMS = 14,
        NO_SALE = 46,
        OPEN_ITEM = 53,
        OPEN_TABLE_TAB = 7,
        ORDER_ITEMS = 11,
        PAID_IN = 40,
        PAID_OUT = 41,
        PRINT_CHECK = 15,
        PRINT_CHECKOUT = 43,
        RECALL_CHECK = 24,
        REFUND_ITEMS = 51,
        REFUND_ORDER = 50,
        REOPEN_CHECK = 23,
        REPORT_RAN = 55,
        RETURN_CHECK = 21,
        SELECT_ORDER = 25,
        SPLIT_ITEM = 16,
        SUBTOTAL = 49,
        TAX = 47,
        TAX_EXEMPT = 52,
        TOTAL = 59,
        TRANSFER_CHECK = 17,
        TRANSFER_TABLE = 18,
        VOID_ITEM = 10,
        VOID_ORDER = 60
    }
}
