//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="IAuthenticateServiceSoap", Namespace="http://3vr.com")]
public partial class IAuthenticateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private SoapHeaderInfo soapHeaderInfoValueField;
    
    private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
    
    private System.Threading.SendOrPostCallback AuthenticateHashedOperationCompleted;
    
    /// <remarks/>
    public IAuthenticateService() {
        this.Url = "http://10.100.2.44/3vr/IAuthenticateService.asmx";
    }
    
    public SoapHeaderInfo SoapHeaderInfoValue {
        get {
            return this.soapHeaderInfoValueField;
        }
        set {
            this.soapHeaderInfoValueField = value;
        }
    }
    
    /// <remarks/>
    public event AuthenticateCompletedEventHandler AuthenticateCompleted;
    
    /// <remarks/>
    public event AuthenticateHashedCompletedEventHandler AuthenticateHashedCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/Authenticate", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public AuthenticateToken Authenticate(string username, string password) {
        object[] results = this.Invoke("Authenticate", new object[] {
                    username,
                    password});
        return ((AuthenticateToken)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAuthenticate(string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Authenticate", new object[] {
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public AuthenticateToken EndAuthenticate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((AuthenticateToken)(results[0]));
    }
    
    /// <remarks/>
    public void AuthenticateAsync(string username, string password) {
        this.AuthenticateAsync(username, password, null);
    }
    
    /// <remarks/>
    public void AuthenticateAsync(string username, string password, object userState) {
        if ((this.AuthenticateOperationCompleted == null)) {
            this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
        }
        this.InvokeAsync("Authenticate", new object[] {
                    username,
                    password}, this.AuthenticateOperationCompleted, userState);
    }
    
    private void OnAuthenticateOperationCompleted(object arg) {
        if ((this.AuthenticateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/AuthenticateHashed", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public AuthenticateToken AuthenticateHashed(string username, string passwordHash) {
        object[] results = this.Invoke("AuthenticateHashed", new object[] {
                    username,
                    passwordHash});
        return ((AuthenticateToken)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAuthenticateHashed(string username, string passwordHash, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AuthenticateHashed", new object[] {
                    username,
                    passwordHash}, callback, asyncState);
    }
    
    /// <remarks/>
    public AuthenticateToken EndAuthenticateHashed(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((AuthenticateToken)(results[0]));
    }
    
    /// <remarks/>
    public void AuthenticateHashedAsync(string username, string passwordHash) {
        this.AuthenticateHashedAsync(username, passwordHash, null);
    }
    
    /// <remarks/>
    public void AuthenticateHashedAsync(string username, string passwordHash, object userState) {
        if ((this.AuthenticateHashedOperationCompleted == null)) {
            this.AuthenticateHashedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateHashedOperationCompleted);
        }
        this.InvokeAsync("AuthenticateHashed", new object[] {
                    username,
                    passwordHash}, this.AuthenticateHashedOperationCompleted, userState);
    }
    
    private void OnAuthenticateHashedOperationCompleted(object arg) {
        if ((this.AuthenticateHashedCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AuthenticateHashedCompleted(this, new AuthenticateHashedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://3vr.com", IsNullable=false)]
//public partial class SoapHeaderInfo : System.Web.Services.Protocols.SoapHeader {
    
//    private string addressField;
    
//    private string serviceTokenField;
    
//    private System.Xml.XmlAttribute[] anyAttrField;
    
//    /// <remarks/>
//    public string Address {
//        get {
//            return this.addressField;
//        }
//        set {
//            this.addressField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string ServiceToken {
//        get {
//            return this.serviceTokenField;
//        }
//        set {
//            this.serviceTokenField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
//    public System.Xml.XmlAttribute[] AnyAttr {
//        get {
//            return this.anyAttrField;
//        }
//        set {
//            this.anyAttrField = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class AuthenticateToken {
    
    private string tokenField;
    
    private string statusField;
    
    /// <remarks/>
    public string Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public AuthenticateToken Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((AuthenticateToken)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void AuthenticateHashedCompletedEventHandler(object sender, AuthenticateHashedCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AuthenticateHashedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AuthenticateHashedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public AuthenticateToken Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((AuthenticateToken)(this.results[0]));
        }
    }
}
