//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="IGenericEventServiceSoap", Namespace="http://3vr.com")]
public partial class IGenericEventService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private SoapHeaderInfo soapHeaderInfoValueField;
    
    private System.Threading.SendOrPostCallback CreateGenericEventDefinitionOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateGenericEventDefinitionOperationCompleted;
    
    private System.Threading.SendOrPostCallback GenericEventDefinitionsByNameOperationCompleted;
    
    private System.Threading.SendOrPostCallback GenericEventDefinitionByGuidOperationCompleted;
    
    private System.Threading.SendOrPostCallback GenericEventDefinitionsAllOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteGenericEventDefinitionOperationCompleted;
    
    private System.Threading.SendOrPostCallback ChannelsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GenericEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateGenericEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateGenericEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateMetaDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateEndTimeOperationCompleted;
    
    private System.Threading.SendOrPostCallback SetEndTimeOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteGenericEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback CustomFieldNamesOperationCompleted;
    
    /// <remarks/>
    public IGenericEventService() {
        this.Url = "http://10.100.2.44/3vr/IGenericEventService.asmx";
    }
    
    public SoapHeaderInfo SoapHeaderInfoValue {
        get {
            return this.soapHeaderInfoValueField;
        }
        set {
            this.soapHeaderInfoValueField = value;
        }
    }
    
    /// <remarks/>
    public event CreateGenericEventDefinitionCompletedEventHandler CreateGenericEventDefinitionCompleted;
    
    /// <remarks/>
    public event UpdateGenericEventDefinitionCompletedEventHandler UpdateGenericEventDefinitionCompleted;
    
    /// <remarks/>
    public event GenericEventDefinitionsByNameCompletedEventHandler GenericEventDefinitionsByNameCompleted;
    
    /// <remarks/>
    public event GenericEventDefinitionByGuidCompletedEventHandler GenericEventDefinitionByGuidCompleted;
    
    /// <remarks/>
    public event GenericEventDefinitionsAllCompletedEventHandler GenericEventDefinitionsAllCompleted;
    
    /// <remarks/>
    public event DeleteGenericEventDefinitionCompletedEventHandler DeleteGenericEventDefinitionCompleted;
    
    /// <remarks/>
    public event ChannelsCompletedEventHandler ChannelsCompleted;
    
    /// <remarks/>
    public event GenericEventCompletedEventHandler GenericEventCompleted;
    
    /// <remarks/>
    public event CreateGenericEventCompletedEventHandler CreateGenericEventCompleted;
    
    /// <remarks/>
    public event UpdateGenericEventCompletedEventHandler UpdateGenericEventCompleted;
    
    /// <remarks/>
    public event UpdateMetaDataCompletedEventHandler UpdateMetaDataCompleted;
    
    /// <remarks/>
    public event UpdateEndTimeCompletedEventHandler UpdateEndTimeCompleted;
    
    /// <remarks/>
    public event SetEndTimeCompletedEventHandler SetEndTimeCompleted;
    
    /// <remarks/>
    public event DeleteGenericEventCompletedEventHandler DeleteGenericEventCompleted;
    
    /// <remarks/>
    public event CustomFieldNamesCompletedEventHandler CustomFieldNamesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/CreateGenericEventDefinition", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventDefinitionData CreateGenericEventDefinition(EventDefinitionData eventDefinition) {
        object[] results = this.Invoke("CreateGenericEventDefinition", new object[] {
                    eventDefinition});
        return ((EventDefinitionData)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateGenericEventDefinition(EventDefinitionData eventDefinition, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateGenericEventDefinition", new object[] {
                    eventDefinition}, callback, asyncState);
    }
    
    /// <remarks/>
    public EventDefinitionData EndCreateGenericEventDefinition(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventDefinitionData)(results[0]));
    }
    
    /// <remarks/>
    public void CreateGenericEventDefinitionAsync(EventDefinitionData eventDefinition) {
        this.CreateGenericEventDefinitionAsync(eventDefinition, null);
    }
    
    /// <remarks/>
    public void CreateGenericEventDefinitionAsync(EventDefinitionData eventDefinition, object userState) {
        if ((this.CreateGenericEventDefinitionOperationCompleted == null)) {
            this.CreateGenericEventDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateGenericEventDefinitionOperationCompleted);
        }
        this.InvokeAsync("CreateGenericEventDefinition", new object[] {
                    eventDefinition}, this.CreateGenericEventDefinitionOperationCompleted, userState);
    }
    
    private void OnCreateGenericEventDefinitionOperationCompleted(object arg) {
        if ((this.CreateGenericEventDefinitionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateGenericEventDefinitionCompleted(this, new CreateGenericEventDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/UpdateGenericEventDefinition", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventDefinitionData UpdateGenericEventDefinition(EventDefinitionData eventDefinition) {
        object[] results = this.Invoke("UpdateGenericEventDefinition", new object[] {
                    eventDefinition});
        return ((EventDefinitionData)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateGenericEventDefinition(EventDefinitionData eventDefinition, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateGenericEventDefinition", new object[] {
                    eventDefinition}, callback, asyncState);
    }
    
    /// <remarks/>
    public EventDefinitionData EndUpdateGenericEventDefinition(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventDefinitionData)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateGenericEventDefinitionAsync(EventDefinitionData eventDefinition) {
        this.UpdateGenericEventDefinitionAsync(eventDefinition, null);
    }
    
    /// <remarks/>
    public void UpdateGenericEventDefinitionAsync(EventDefinitionData eventDefinition, object userState) {
        if ((this.UpdateGenericEventDefinitionOperationCompleted == null)) {
            this.UpdateGenericEventDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGenericEventDefinitionOperationCompleted);
        }
        this.InvokeAsync("UpdateGenericEventDefinition", new object[] {
                    eventDefinition}, this.UpdateGenericEventDefinitionOperationCompleted, userState);
    }
    
    private void OnUpdateGenericEventDefinitionOperationCompleted(object arg) {
        if ((this.UpdateGenericEventDefinitionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateGenericEventDefinitionCompleted(this, new UpdateGenericEventDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/GenericEventDefinitionsByName", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventDefinitionData[] GenericEventDefinitionsByName(string name) {
        object[] results = this.Invoke("GenericEventDefinitionsByName", new object[] {
                    name});
        return ((EventDefinitionData[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGenericEventDefinitionsByName(string name, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GenericEventDefinitionsByName", new object[] {
                    name}, callback, asyncState);
    }
    
    /// <remarks/>
    public EventDefinitionData[] EndGenericEventDefinitionsByName(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventDefinitionData[])(results[0]));
    }
    
    /// <remarks/>
    public void GenericEventDefinitionsByNameAsync(string name) {
        this.GenericEventDefinitionsByNameAsync(name, null);
    }
    
    /// <remarks/>
    public void GenericEventDefinitionsByNameAsync(string name, object userState) {
        if ((this.GenericEventDefinitionsByNameOperationCompleted == null)) {
            this.GenericEventDefinitionsByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenericEventDefinitionsByNameOperationCompleted);
        }
        this.InvokeAsync("GenericEventDefinitionsByName", new object[] {
                    name}, this.GenericEventDefinitionsByNameOperationCompleted, userState);
    }
    
    private void OnGenericEventDefinitionsByNameOperationCompleted(object arg) {
        if ((this.GenericEventDefinitionsByNameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GenericEventDefinitionsByNameCompleted(this, new GenericEventDefinitionsByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/GenericEventDefinitionByGuid", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventDefinitionData GenericEventDefinitionByGuid(System.Guid guid) {
        object[] results = this.Invoke("GenericEventDefinitionByGuid", new object[] {
                    guid});
        return ((EventDefinitionData)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGenericEventDefinitionByGuid(System.Guid guid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GenericEventDefinitionByGuid", new object[] {
                    guid}, callback, asyncState);
    }
    
    /// <remarks/>
    public EventDefinitionData EndGenericEventDefinitionByGuid(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventDefinitionData)(results[0]));
    }
    
    /// <remarks/>
    public void GenericEventDefinitionByGuidAsync(System.Guid guid) {
        this.GenericEventDefinitionByGuidAsync(guid, null);
    }
    
    /// <remarks/>
    public void GenericEventDefinitionByGuidAsync(System.Guid guid, object userState) {
        if ((this.GenericEventDefinitionByGuidOperationCompleted == null)) {
            this.GenericEventDefinitionByGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenericEventDefinitionByGuidOperationCompleted);
        }
        this.InvokeAsync("GenericEventDefinitionByGuid", new object[] {
                    guid}, this.GenericEventDefinitionByGuidOperationCompleted, userState);
    }
    
    private void OnGenericEventDefinitionByGuidOperationCompleted(object arg) {
        if ((this.GenericEventDefinitionByGuidCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GenericEventDefinitionByGuidCompleted(this, new GenericEventDefinitionByGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/GenericEventDefinitionsAll", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventDefinitionData[] GenericEventDefinitionsAll() {
        object[] results = this.Invoke("GenericEventDefinitionsAll", new object[0]);
        return ((EventDefinitionData[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGenericEventDefinitionsAll(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GenericEventDefinitionsAll", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public EventDefinitionData[] EndGenericEventDefinitionsAll(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventDefinitionData[])(results[0]));
    }
    
    /// <remarks/>
    public void GenericEventDefinitionsAllAsync() {
        this.GenericEventDefinitionsAllAsync(null);
    }
    
    /// <remarks/>
    public void GenericEventDefinitionsAllAsync(object userState) {
        if ((this.GenericEventDefinitionsAllOperationCompleted == null)) {
            this.GenericEventDefinitionsAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenericEventDefinitionsAllOperationCompleted);
        }
        this.InvokeAsync("GenericEventDefinitionsAll", new object[0], this.GenericEventDefinitionsAllOperationCompleted, userState);
    }
    
    private void OnGenericEventDefinitionsAllOperationCompleted(object arg) {
        if ((this.GenericEventDefinitionsAllCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GenericEventDefinitionsAllCompleted(this, new GenericEventDefinitionsAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/DeleteGenericEventDefinition", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string DeleteGenericEventDefinition(System.Guid guid) {
        object[] results = this.Invoke("DeleteGenericEventDefinition", new object[] {
                    guid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteGenericEventDefinition(System.Guid guid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteGenericEventDefinition", new object[] {
                    guid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDeleteGenericEventDefinition(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteGenericEventDefinitionAsync(System.Guid guid) {
        this.DeleteGenericEventDefinitionAsync(guid, null);
    }
    
    /// <remarks/>
    public void DeleteGenericEventDefinitionAsync(System.Guid guid, object userState) {
        if ((this.DeleteGenericEventDefinitionOperationCompleted == null)) {
            this.DeleteGenericEventDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGenericEventDefinitionOperationCompleted);
        }
        this.InvokeAsync("DeleteGenericEventDefinition", new object[] {
                    guid}, this.DeleteGenericEventDefinitionOperationCompleted, userState);
    }
    
    private void OnDeleteGenericEventDefinitionOperationCompleted(object arg) {
        if ((this.DeleteGenericEventDefinitionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteGenericEventDefinitionCompleted(this, new DeleteGenericEventDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/Channels", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChannelInfo[] Channels() {
        object[] results = this.Invoke("Channels", new object[0]);
        return ((ChannelInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginChannels(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Channels", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChannelInfo[] EndChannels(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChannelInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void ChannelsAsync() {
        this.ChannelsAsync(null);
    }
    
    /// <remarks/>
    public void ChannelsAsync(object userState) {
        if ((this.ChannelsOperationCompleted == null)) {
            this.ChannelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChannelsOperationCompleted);
        }
        this.InvokeAsync("Channels", new object[0], this.ChannelsOperationCompleted, userState);
    }
    
    private void OnChannelsOperationCompleted(object arg) {
        if ((this.ChannelsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ChannelsCompleted(this, new ChannelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/GenericEvent", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public GenericEventData GenericEvent(System.Guid guid) {
        object[] results = this.Invoke("GenericEvent", new object[] {
                    guid});
        return ((GenericEventData)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGenericEvent(System.Guid guid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GenericEvent", new object[] {
                    guid}, callback, asyncState);
    }
    
    /// <remarks/>
    public GenericEventData EndGenericEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((GenericEventData)(results[0]));
    }
    
    /// <remarks/>
    public void GenericEventAsync(System.Guid guid) {
        this.GenericEventAsync(guid, null);
    }
    
    /// <remarks/>
    public void GenericEventAsync(System.Guid guid, object userState) {
        if ((this.GenericEventOperationCompleted == null)) {
            this.GenericEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenericEventOperationCompleted);
        }
        this.InvokeAsync("GenericEvent", new object[] {
                    guid}, this.GenericEventOperationCompleted, userState);
    }
    
    private void OnGenericEventOperationCompleted(object arg) {
        if ((this.GenericEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GenericEventCompleted(this, new GenericEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/CreateGenericEvent", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Guid CreateGenericEvent(GenericEventData genericEvent) {
        object[] results = this.Invoke("CreateGenericEvent", new object[] {
                    genericEvent});
        return ((System.Guid)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateGenericEvent(GenericEventData genericEvent, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateGenericEvent", new object[] {
                    genericEvent}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Guid EndCreateGenericEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Guid)(results[0]));
    }
    
    /// <remarks/>
    public void CreateGenericEventAsync(GenericEventData genericEvent) {
        this.CreateGenericEventAsync(genericEvent, null);
    }
    
    /// <remarks/>
    public void CreateGenericEventAsync(GenericEventData genericEvent, object userState) {
        if ((this.CreateGenericEventOperationCompleted == null)) {
            this.CreateGenericEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateGenericEventOperationCompleted);
        }
        this.InvokeAsync("CreateGenericEvent", new object[] {
                    genericEvent}, this.CreateGenericEventOperationCompleted, userState);
    }
    
    private void OnCreateGenericEventOperationCompleted(object arg) {
        if ((this.CreateGenericEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateGenericEventCompleted(this, new CreateGenericEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/UpdateGenericEvent", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Guid UpdateGenericEvent(GenericEventData genericEvent) {
        object[] results = this.Invoke("UpdateGenericEvent", new object[] {
                    genericEvent});
        return ((System.Guid)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateGenericEvent(GenericEventData genericEvent, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateGenericEvent", new object[] {
                    genericEvent}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Guid EndUpdateGenericEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Guid)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateGenericEventAsync(GenericEventData genericEvent) {
        this.UpdateGenericEventAsync(genericEvent, null);
    }
    
    /// <remarks/>
    public void UpdateGenericEventAsync(GenericEventData genericEvent, object userState) {
        if ((this.UpdateGenericEventOperationCompleted == null)) {
            this.UpdateGenericEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGenericEventOperationCompleted);
        }
        this.InvokeAsync("UpdateGenericEvent", new object[] {
                    genericEvent}, this.UpdateGenericEventOperationCompleted, userState);
    }
    
    private void OnUpdateGenericEventOperationCompleted(object arg) {
        if ((this.UpdateGenericEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateGenericEventCompleted(this, new UpdateGenericEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/UpdateMetaData", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UpdateMetaData(System.Guid eventGuid, bool useServerTime, GenericEventMetadata[] metadataList) {
        this.Invoke("UpdateMetaData", new object[] {
                    eventGuid,
                    useServerTime,
                    metadataList});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateMetaData(System.Guid eventGuid, bool useServerTime, GenericEventMetadata[] metadataList, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateMetaData", new object[] {
                    eventGuid,
                    useServerTime,
                    metadataList}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUpdateMetaData(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UpdateMetaDataAsync(System.Guid eventGuid, bool useServerTime, GenericEventMetadata[] metadataList) {
        this.UpdateMetaDataAsync(eventGuid, useServerTime, metadataList, null);
    }
    
    /// <remarks/>
    public void UpdateMetaDataAsync(System.Guid eventGuid, bool useServerTime, GenericEventMetadata[] metadataList, object userState) {
        if ((this.UpdateMetaDataOperationCompleted == null)) {
            this.UpdateMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMetaDataOperationCompleted);
        }
        this.InvokeAsync("UpdateMetaData", new object[] {
                    eventGuid,
                    useServerTime,
                    metadataList}, this.UpdateMetaDataOperationCompleted, userState);
    }
    
    private void OnUpdateMetaDataOperationCompleted(object arg) {
        if ((this.UpdateMetaDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateMetaDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/UpdateEndTime", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UpdateEndTime(System.Guid eventGuid, System.DateTime timestamp) {
        this.Invoke("UpdateEndTime", new object[] {
                    eventGuid,
                    timestamp});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateEndTime(System.Guid eventGuid, System.DateTime timestamp, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateEndTime", new object[] {
                    eventGuid,
                    timestamp}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUpdateEndTime(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UpdateEndTimeAsync(System.Guid eventGuid, System.DateTime timestamp) {
        this.UpdateEndTimeAsync(eventGuid, timestamp, null);
    }
    
    /// <remarks/>
    public void UpdateEndTimeAsync(System.Guid eventGuid, System.DateTime timestamp, object userState) {
        if ((this.UpdateEndTimeOperationCompleted == null)) {
            this.UpdateEndTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEndTimeOperationCompleted);
        }
        this.InvokeAsync("UpdateEndTime", new object[] {
                    eventGuid,
                    timestamp}, this.UpdateEndTimeOperationCompleted, userState);
    }
    
    private void OnUpdateEndTimeOperationCompleted(object arg) {
        if ((this.UpdateEndTimeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateEndTimeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/SetEndTime", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SetEndTime(System.Guid eventGuid, long delta) {
        this.Invoke("SetEndTime", new object[] {
                    eventGuid,
                    delta});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSetEndTime(System.Guid eventGuid, long delta, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SetEndTime", new object[] {
                    eventGuid,
                    delta}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSetEndTime(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SetEndTimeAsync(System.Guid eventGuid, long delta) {
        this.SetEndTimeAsync(eventGuid, delta, null);
    }
    
    /// <remarks/>
    public void SetEndTimeAsync(System.Guid eventGuid, long delta, object userState) {
        if ((this.SetEndTimeOperationCompleted == null)) {
            this.SetEndTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetEndTimeOperationCompleted);
        }
        this.InvokeAsync("SetEndTime", new object[] {
                    eventGuid,
                    delta}, this.SetEndTimeOperationCompleted, userState);
    }
    
    private void OnSetEndTimeOperationCompleted(object arg) {
        if ((this.SetEndTimeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SetEndTimeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/DeleteGenericEvent", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Guid DeleteGenericEvent(System.Guid guid) {
        object[] results = this.Invoke("DeleteGenericEvent", new object[] {
                    guid});
        return ((System.Guid)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteGenericEvent(System.Guid guid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteGenericEvent", new object[] {
                    guid}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Guid EndDeleteGenericEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Guid)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteGenericEventAsync(System.Guid guid) {
        this.DeleteGenericEventAsync(guid, null);
    }
    
    /// <remarks/>
    public void DeleteGenericEventAsync(System.Guid guid, object userState) {
        if ((this.DeleteGenericEventOperationCompleted == null)) {
            this.DeleteGenericEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGenericEventOperationCompleted);
        }
        this.InvokeAsync("DeleteGenericEvent", new object[] {
                    guid}, this.DeleteGenericEventOperationCompleted, userState);
    }
    
    private void OnDeleteGenericEventOperationCompleted(object arg) {
        if ((this.DeleteGenericEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteGenericEventCompleted(this, new DeleteGenericEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHeaderInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://3vr.com/CustomFieldNames", RequestNamespace="http://3vr.com", ResponseNamespace="http://3vr.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] CustomFieldNames() {
        object[] results = this.Invoke("CustomFieldNames", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCustomFieldNames(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CustomFieldNames", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndCustomFieldNames(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void CustomFieldNamesAsync() {
        this.CustomFieldNamesAsync(null);
    }
    
    /// <remarks/>
    public void CustomFieldNamesAsync(object userState) {
        if ((this.CustomFieldNamesOperationCompleted == null)) {
            this.CustomFieldNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomFieldNamesOperationCompleted);
        }
        this.InvokeAsync("CustomFieldNames", new object[0], this.CustomFieldNamesOperationCompleted, userState);
    }
    
    private void OnCustomFieldNamesOperationCompleted(object arg) {
        if ((this.CustomFieldNamesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CustomFieldNamesCompleted(this, new CustomFieldNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://3vr.com", IsNullable=false)]
public partial class SoapHeaderInfo : System.Web.Services.Protocols.SoapHeader {
    
    private string addressField;
    
    private string serviceTokenField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceToken {
        get {
            return this.serviceTokenField;
        }
        set {
            this.serviceTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class ReferenceComparison {
    
    private int startTimeReferenceDeltaField;
    
    private int endTimeReferenceDeltaField;
    
    private GenericEventImage referenceImageField;
    
    private string customFieldNameField;
    
    private string customFieldValueField;
    
    /// <remarks/>
    public int StartTimeReferenceDelta {
        get {
            return this.startTimeReferenceDeltaField;
        }
        set {
            this.startTimeReferenceDeltaField = value;
        }
    }
    
    /// <remarks/>
    public int EndTimeReferenceDelta {
        get {
            return this.endTimeReferenceDeltaField;
        }
        set {
            this.endTimeReferenceDeltaField = value;
        }
    }
    
    /// <remarks/>
    public GenericEventImage ReferenceImage {
        get {
            return this.referenceImageField;
        }
        set {
            this.referenceImageField = value;
        }
    }
    
    /// <remarks/>
    public string CustomFieldName {
        get {
            return this.customFieldNameField;
        }
        set {
            this.customFieldNameField = value;
        }
    }
    
    /// <remarks/>
    public string CustomFieldValue {
        get {
            return this.customFieldValueField;
        }
        set {
            this.customFieldValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class GenericEventImage {
    
    private int widthField;
    
    private int heightField;
    
    private PictureFormat formatField;
    
    private uint nominalAspectRatioField;
    
    private double aspectRatioAdjustmentField;
    
    private byte[] imageBufferField;
    
    private int displayPositionField;
    
    private RectangleF displayRectField;
    
    private System.DateTime imageTimeField;
    
    /// <remarks/>
    public int Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public int Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public PictureFormat Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    public uint NominalAspectRatio {
        get {
            return this.nominalAspectRatioField;
        }
        set {
            this.nominalAspectRatioField = value;
        }
    }
    
    /// <remarks/>
    public double AspectRatioAdjustment {
        get {
            return this.aspectRatioAdjustmentField;
        }
        set {
            this.aspectRatioAdjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] ImageBuffer {
        get {
            return this.imageBufferField;
        }
        set {
            this.imageBufferField = value;
        }
    }
    
    /// <remarks/>
    public int DisplayPosition {
        get {
            return this.displayPositionField;
        }
        set {
            this.displayPositionField = value;
        }
    }
    
    /// <remarks/>
    public RectangleF DisplayRect {
        get {
            return this.displayRectField;
        }
        set {
            this.displayRectField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ImageTime {
        get {
            return this.imageTimeField;
        }
        set {
            this.imageTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public enum PictureFormat {
    
    /// <remarks/>
    Unknown,
    
    /// <remarks/>
    Yuv444,
    
    /// <remarks/>
    Yuv420,
    
    /// <remarks/>
    Grayscale,
    
    /// <remarks/>
    GrayscaleRgb,
    
    /// <remarks/>
    Rgb,
    
    /// <remarks/>
    Jpeg,
    
    /// <remarks/>
    Bitmap,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class RectangleF {
    
    private PointF locationField;
    
    private SizeF sizeField;
    
    private float xField;
    
    private float yField;
    
    private float widthField;
    
    private float heightField;
    
    /// <remarks/>
    public PointF Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public SizeF Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public float X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public float Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    public float Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public float Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class PointF {
    
    private float xField;
    
    private float yField;
    
    /// <remarks/>
    public float X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public float Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class SizeF {
    
    private float widthField;
    
    private float heightField;
    
    /// <remarks/>
    public float Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public float Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class GenericEventMetadata {
    
    private System.Guid guidField;
    
    private MimeType mimeTypeField;
    
    private System.DateTime beginTimeField;
    
    private System.DateTime endTimeField;
    
    private string valueField;
    
    /// <remarks/>
    public System.Guid Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public MimeType MimeType {
        get {
            return this.mimeTypeField;
        }
        set {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime BeginTime {
        get {
            return this.beginTimeField;
        }
        set {
            this.beginTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EndTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public enum MimeType {
    
    /// <remarks/>
    Unknown,
    
    /// <remarks/>
    Custom,
    
    /// <remarks/>
    Audio,
    
    /// <remarks/>
    Video,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class GenericEventData {
    
    private System.Guid guidField;
    
    private int startTimeDeltaField;
    
    private int endTimeDeltaField;
    
    private bool useServerTimeField;
    
    private long channelIdField;
    
    private System.Guid definitionGuidField;
    
    private GenericEventMetadata[] metadataListField;
    
    private GenericEventImage[] imagesField;
    
    private bool closeEventField;
    
    private bool searchOutsideEventForFrameField;
    
    private ReferenceComparison faceComparisonField;
    
    private System.DateTime eventTimeField;
    
    /// <remarks/>
    public System.Guid Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public int StartTimeDelta {
        get {
            return this.startTimeDeltaField;
        }
        set {
            this.startTimeDeltaField = value;
        }
    }
    
    /// <remarks/>
    public int EndTimeDelta {
        get {
            return this.endTimeDeltaField;
        }
        set {
            this.endTimeDeltaField = value;
        }
    }
    
    /// <remarks/>
    public bool UseServerTime {
        get {
            return this.useServerTimeField;
        }
        set {
            this.useServerTimeField = value;
        }
    }
    
    /// <remarks/>
    public long ChannelId {
        get {
            return this.channelIdField;
        }
        set {
            this.channelIdField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid DefinitionGuid {
        get {
            return this.definitionGuidField;
        }
        set {
            this.definitionGuidField = value;
        }
    }
    
    /// <remarks/>
    public GenericEventMetadata[] MetadataList {
        get {
            return this.metadataListField;
        }
        set {
            this.metadataListField = value;
        }
    }
    
    /// <remarks/>
    public GenericEventImage[] Images {
        get {
            return this.imagesField;
        }
        set {
            this.imagesField = value;
        }
    }
    
    /// <remarks/>
    public bool CloseEvent {
        get {
            return this.closeEventField;
        }
        set {
            this.closeEventField = value;
        }
    }
    
    /// <remarks/>
    public bool SearchOutsideEventForFrame {
        get {
            return this.searchOutsideEventForFrameField;
        }
        set {
            this.searchOutsideEventForFrameField = value;
        }
    }
    
    /// <remarks/>
    public ReferenceComparison FaceComparison {
        get {
            return this.faceComparisonField;
        }
        set {
            this.faceComparisonField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EventTime {
        get {
            return this.eventTimeField;
        }
        set {
            this.eventTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class ChannelInfo {
    
    private long idField;
    
    private string nameField;
    
    private int displayNumberField;
    
    private string identifierField;
    
    private string descriptionField;
    
    private string hostNameField;
    
    private bool isActiveField;
    
    /// <remarks/>
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public int DisplayNumber {
        get {
            return this.displayNumberField;
        }
        set {
            this.displayNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string HostName {
        get {
            return this.hostNameField;
        }
        set {
            this.hostNameField = value;
        }
    }
    
    /// <remarks/>
    public bool IsActive {
        get {
            return this.isActiveField;
        }
        set {
            this.isActiveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class EnumeratedData {
    
    private string nameField;
    
    private string[] valuesField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string[] Values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class MetadataField {
    
    private System.Guid guidField;
    
    private string nameField;
    
    private string descriptionField;
    
    private MetadataType typeField;
    
    private int displayPositionField;
    
    private string displayFormatField;
    
    private string formatField;
    
    private bool allowUserEditField;
    
    private bool isOverlayField;
    
    private StreamTimeUsage streamTimeUsageField;
    
    private bool isMultipleField;
    
    private EnumeratedData enumeratedDataField;
    
    /// <remarks/>
    public System.Guid Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public MetadataType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public int DisplayPosition {
        get {
            return this.displayPositionField;
        }
        set {
            this.displayPositionField = value;
        }
    }
    
    /// <remarks/>
    public string DisplayFormat {
        get {
            return this.displayFormatField;
        }
        set {
            this.displayFormatField = value;
        }
    }
    
    /// <remarks/>
    public string Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    public bool AllowUserEdit {
        get {
            return this.allowUserEditField;
        }
        set {
            this.allowUserEditField = value;
        }
    }
    
    /// <remarks/>
    public bool IsOverlay {
        get {
            return this.isOverlayField;
        }
        set {
            this.isOverlayField = value;
        }
    }
    
    /// <remarks/>
    public StreamTimeUsage StreamTimeUsage {
        get {
            return this.streamTimeUsageField;
        }
        set {
            this.streamTimeUsageField = value;
        }
    }
    
    /// <remarks/>
    public bool IsMultiple {
        get {
            return this.isMultipleField;
        }
        set {
            this.isMultipleField = value;
        }
    }
    
    /// <remarks/>
    public EnumeratedData EnumeratedData {
        get {
            return this.enumeratedDataField;
        }
        set {
            this.enumeratedDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public enum MetadataType {
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Number,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    EnumeratedType,
    
    /// <remarks/>
    Binary,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public enum StreamTimeUsage {
    
    /// <remarks/>
    Ignore,
    
    /// <remarks/>
    Single,
    
    /// <remarks/>
    Range,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://3vr.com")]
public partial class EventDefinitionData {
    
    private string nameField;
    
    private string shortNameField;
    
    private System.Guid guidField;
    
    private string helpTextField;
    
    private bool isTransactionField;
    
    private int numberCardImagesField;
    
    private MetadataField[] metadataFieldsField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string ShortName {
        get {
            return this.shortNameField;
        }
        set {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string HelpText {
        get {
            return this.helpTextField;
        }
        set {
            this.helpTextField = value;
        }
    }
    
    /// <remarks/>
    public bool IsTransaction {
        get {
            return this.isTransactionField;
        }
        set {
            this.isTransactionField = value;
        }
    }
    
    /// <remarks/>
    public int NumberCardImages {
        get {
            return this.numberCardImagesField;
        }
        set {
            this.numberCardImagesField = value;
        }
    }
    
    /// <remarks/>
    public MetadataField[] MetadataFields {
        get {
            return this.metadataFieldsField;
        }
        set {
            this.metadataFieldsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void CreateGenericEventDefinitionCompletedEventHandler(object sender, CreateGenericEventDefinitionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateGenericEventDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateGenericEventDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventDefinitionData Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventDefinitionData)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void UpdateGenericEventDefinitionCompletedEventHandler(object sender, UpdateGenericEventDefinitionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateGenericEventDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateGenericEventDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventDefinitionData Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventDefinitionData)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GenericEventDefinitionsByNameCompletedEventHandler(object sender, GenericEventDefinitionsByNameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GenericEventDefinitionsByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GenericEventDefinitionsByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventDefinitionData[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventDefinitionData[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GenericEventDefinitionByGuidCompletedEventHandler(object sender, GenericEventDefinitionByGuidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GenericEventDefinitionByGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GenericEventDefinitionByGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventDefinitionData Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventDefinitionData)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GenericEventDefinitionsAllCompletedEventHandler(object sender, GenericEventDefinitionsAllCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GenericEventDefinitionsAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GenericEventDefinitionsAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventDefinitionData[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventDefinitionData[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void DeleteGenericEventDefinitionCompletedEventHandler(object sender, DeleteGenericEventDefinitionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteGenericEventDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteGenericEventDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void ChannelsCompletedEventHandler(object sender, ChannelsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChannelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ChannelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChannelInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChannelInfo[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GenericEventCompletedEventHandler(object sender, GenericEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GenericEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GenericEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public GenericEventData Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((GenericEventData)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void CreateGenericEventCompletedEventHandler(object sender, CreateGenericEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateGenericEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateGenericEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Guid Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Guid)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void UpdateGenericEventCompletedEventHandler(object sender, UpdateGenericEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateGenericEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateGenericEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Guid Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Guid)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void UpdateMetaDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void UpdateEndTimeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SetEndTimeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void DeleteGenericEventCompletedEventHandler(object sender, DeleteGenericEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteGenericEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteGenericEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Guid Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Guid)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void CustomFieldNamesCompletedEventHandler(object sender, CustomFieldNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CustomFieldNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CustomFieldNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}
